services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: ["5432:5432"]
    volumes:
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  ai:
    build: ./services/ai
    ports: ["8000:8000"]

  api:
    build: ./services/api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AI_URL: http://ai:8000
    ports: ["3001:8080"]
    depends_on: [db, ai]

  web:
    build: ./services/web
    environment:
      VITE_API_URL: http://localhost:3001
    ports: ["5173:5173"]
    depends_on: [api]
